server {
    listen 0.0.0.0:80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Handle Astro's static routes
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Redirect 404s to the main page or a 404 page if you create one later
    error_page 404 /index.html;

    # Enable Gzip compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
